---
title: "My English Activity Log : MEAL"
author:
  - name: "Nicolas Neels" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
---

- September 2020 : I downloaded the 'BBC News' and the 'wordreference' Apps on my phone. I don't use the BBC app actively but i enjoy receiving notifications that inform me about important topics

- Oct. 24th : I realised we had a M.E.A.L. page on our blog so I felt pretty blind and tried to think of what I did in English. It isn't very easy since I do a lot of things in English. Playing video-games or watching online videos (e.g. : on Youtube) requires to use English a lot. When I watch series (e.g. :Game of Thrones), I do it in English with English subtitles.

- Oct. 24th : My very first article is finished and posted on my blog. I'm starting to feel comfortable with how RStudio works. This is always a good thing!

- Oct. 25th : My blog now has a new character font and design. I wanted to change the background color with a blue-ish white but it made it look sad so I didn't do it.

- Oct. 28th : disqus is finally running on my blog! Feel free to comment whatever you would like. It could be a constructive advice, a funny line or simply saying hi ;-)

- Nov. 1st : The second article is now online; if you like sauropods, you should definitely check it out ^^

- Nov. 16th : I just made an article with an interactive dendrogram about Jurassic Park dinosaurs. I spent a lot of time searching for information so feel free to give me some feedback!

- Febr. 24th : I have finally seen the South Park movie. It truly was outstanding! I am quite a fan of this series because it is about societal problems and treats and describes them with humor, through the eyes of children. I have watched all episodes so far (in original version; i don't like the French voices) and have just finished viewing the film. Honestly, if you are not afraid of bad language, I warmly recommend you this series!

- March. 6th : Hello everyone! I'm back for new articles! I had to pause it due to a substantial load of work but I am ready to spoon-feed you with Dino-facts again! By the way, the article 5 is already online!
